### ISSUE TITLE
No visible playback

### ISSUE THREAD

**Issue by cefn** [jianli/git-playback#4]
Just launched git-playback against a file in my repository, and although it seems to be navigating through commits correctly using keyboard shortcuts (as shown by footer line), there's nothing visible in the main screen (unless it's black on black text or something).

The build was installed on Lubuntu 14.10 by running...

    sudo pip install git-playback

**Comment by jianli** [comment]
I'm unable to replicate this in my environment (OS X 10.9.5).

> unless it's black on black text or something

The text should be a combination of black, green, and red, like this:

![git playback README.md](https://raw.github.com/jianli/git-playback/master/animation.gif "git playback README.md")

**Comment by cefn** [comment]
I have been able to replicate this bug with a public repository at https://github.com/cefn/firmware-codesign-readinglog

Running...
git-playback log_paper.sh
...for example, only populates the footer, and no other text is visible at all (empty console screen above the footer line) and certainly no animation of changes.

I can replicate this bug on Lubuntu 14.10 with Gnome Terminal (default purple background), LXTerminal (default black background), Xterm (default black background). An example configuration presents an console with a standard size of 80x24. My login shell is /bin/bash

However, when attempting the same operation within TTY1 (which I can switch to with CTRL+ALT+F1 and log in as a console user) then the colored text becomes visible.

The git-playback command aliases to /usr/local/bin/git-playback which looks like...

~~~
#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'git-playback==0.1','console_scripts','git-playback'
__requires__ = 'git-playback==0.1'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('git-playback==0.1', 'console_scripts', 'git-playback')()
    )
~~~

**Comment by cefn** [comment]
Are there other tools I can test out which would independently verify my system build for the libraries you're using (e.g. another curses-based tool which you would think is equivalent in dependencies, another git-oriented tool which you would think is equivalent in dependencies)?

**Comment by jianli** [comment]
> An example configuration presents an console with a standard size of 80x24

Ah, ok. That's the problem. `git-playback` requires a [console width of 83+](https://github.com/jianli/git-playback/blob/d26e8110491012d38a1b5c56ec5608edddefcf09/playback/__init__.py#L35)

**Comment by cefn** [comment]
I can prove that after resizing the console, the behaviour is as expected. Thanks.

Be great if there was a way of presenting this as an error or warning, rather than a silent failure, especially with standard Terminal sizes being 80 characters in almost every environment I've encountered, inherited from IBM punched card standards then Teletype, but pretty much ubiquitous...
http://en.wikipedia.org/wiki/Text_mode

**Comment by jianli** [comment]
I've changed the program so that it displays at least one column regardless of console width. It will continue to not display secondary columns if there isn't enough space.

My impression (might be wrong) is that very few users keep their terminals as narrow as 80 characters, even if it is the default.
